version: '3.6'

services:
  inews-watcher:
    hostname: inews-to-kafka
    image: calebebrim/inews-ftp-watcher:1
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - CONFIG_PATH=/config
      - PROCESSED_FILE_NAME=processed.json 
      - FTP_CONFIG_FILE_NAME=ftp-config-example.json 
      - KAFKA_CONFIG_FILE_NAME=kafka-config-karafka-cloud.json 
      - FTP_PATH=/Inews
    logging:
      driver: "json-file"
      options:
       max-file: "1"
       max-size: "1g" 